// food-supermarket/src/components/ProductCard.vue
<script setup>
import { defineProps, defineEmits } from 'vue'

const props = defineProps({
    product: Object
})

const emit = defineEmits(["add"])

const handleAdd = () => {
    emit("add", props.product)
}
</script>

<template>
    <div class="col-4">
        <div class="card mb-3">
            <img :src="product.image" class="text-center m-auto mt-4" width="100%" height="200" :alt="product.name" />

            <div class="card-body">
                <h5 class="card-title">{{product.name}}</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>

            <ul class="list-group list-group-flush">
                <li class="list-group-item">{{product.category}}</li>
                <li class="list-group-item">£{{product.price.toFixed(2)}}</li>
            </ul>

            <div class="card-body">
                <button @click="handleAdd" type="button" class="btn btn-sm btn-danger">Add to cart</button>
            </div>
        </div>
    </div>
    
</template>

// bookshop/src/components/ProductCard.jsx
import React from 'react'
import { useDispatch } from 'react-redux'
import { addToCart } from '../store/cart/cartSlice'
import {toast} from 'react-toastify'

function ProductCard({book}) {
  const dispatch = useDispatch()

  const onAddToCart = () => {
    dispatch(addToCart(book))

    toast.success(`${book.title} added to cart}`)
  }

  return (
    <div className='col-4'>
        <div className="card mb-3">
            <img src={book.image} className="text-center m-auto mt-4" width="100" height="100" alt={book.title} />

            <div className="card-body">
                <h5 className="card-title">{book.title}</h5>
                <p className="card-text"><strong>Author:</strong> {book.author}</p>
            </div>

            <ul className="list-group list-group-flush">
                <li className="list-group-item">[{book.category}]</li>
                <li className="list-group-item">£{book.price}</li>
            </ul>

            <div className="card-body">
                <button onClick={onAddToCart} type="button" className="btn btn-sm btn-danger">Add to cart</button>
            </div>
        </div>
    </div>
  )
}

export default ProductCard
